import 'package:flutter/material.dart';
import '../theme/app_theme.dart';

class DisclaimerScreen extends StatelessWidget {
  const DisclaimerScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final textColor = isDark ? AppTheme.darkTextDark : AppTheme.textDark;
    final textGreyColor = isDark ? AppTheme.darkTextGrey : AppTheme.textGrey;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Disclaimer'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'AI-GENERATED OUTPUT — NOT A DIAGNOSIS — MUST BE INDEPENDENTLY VERIFIED',
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
                color: textColor,
              ),
            ),
            const SizedBox(height: 16),
            Text(
              'This report was generated by an artificial intelligence / machine learning algorithm from photographic images of the oral cavity. It is a computer-generated, probabilistic risk estimate produced by pattern matching against a finite training dataset. It is NOT a diagnosis, NOT a pathology report, NOT a radiology report, and NOT a clinical opinion. It has not been authored by a clinician.\n\n'
              'This output must not be read literally, quoted as a finding, or acted upon on its own. It carries no diagnostic authority and must be independently evaluated and confirmed by qualified specialists—an oral pathologist / histopathologist and, where indicated, an oral and maxillofacial surgeon or oncologist—supported by appropriate laboratory and imaging investigations. Histopathological examination of an adequate tissue biopsy remains the only definitive means of diagnosing or excluding oral dysplasia and oral cancer.\n\n'
              'THE ALGORITHM CAN BE WRONG IN BOTH DIRECTIONS:\n\n'
              'A LOW-RISK OR NEGATIVE RESULT DOES NOT EXCLUDE DYSPLASIA OR MALIGNANCY and must never be treated or communicated as reassurance.\n\n'
              'A HIGH-RISK RESULT DOES NOT ESTABLISH DISEASE; many benign conditions produce a high-risk output.\n\n'
              'Accuracy is dependent on image quality, lighting, focus, mucosal retraction, capture device, and patient factors. The output does not account for history, habits, symptom duration, palpation findings, induration, fixity, or cervical lymph node status unless separately entered, and it does not assess sites outside the visually accessible oral mucosa.\n\n'
              'Clinical responsibility rests entirely with the treating registered practitioner. Any clinically suspicious lesion must be referred and biopsied on clinical grounds irrespective of this output. No treatment, surgical, oncological, or prognostic decision may be based on this report.\n\n'
              'ANY PERSISTENT ULCER, WHITE OR RED PATCH, LUMP, NUMBNESS, LOOSE TOOTH, RESTRICTED MOUTH OPENING, OR DIFFICULTY IN SWALLOWING LASTING MORE THAN TWO WEEKS REQUIRES CLINICAL REVIEW, WHATEVER THIS REPORT STATES.',
              style: TextStyle(
                fontSize: 15,
                color: textGreyColor,
                height: 1.6,
              ),
            ),
            const SizedBox(height: 20),
          ],
        ),
      ),
    );
  }
}
